<?php

namespace CCDNForum\KarmaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * KarmaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KarmaRepository extends EntityRepository
{
	
	
	
	/**
	 *
	 * @access public
	 * @param int $topicId
	 */
	public function findKarmaForUserById($userId)
	{
		$query = $this->getEntityManager()
			->createQuery('
				SELECT k FROM CCDNForumKarmaBundle:Karma k
				LEFT JOIN k.posted_by kc
				LEFT JOIN k.for_user kf
				WHERE k.for_user = :id
				ORDER BY k.posted_date DESC')
			->setParameter('id', $userId);

		try {
			return new Pagerfanta(new DoctrineORMAdapter($query));
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
}